stages:
  # 准备系统环境
  - env
  # 安装 k8s
  - install
  # 代码同步
  - sync

variables:
  NEEDRESTART: n
  ANOLIS_URL: http://172.25.25.14:48081/repository/anolis

# 嵌入
include:
  - .gitlab/ci/anolisos-7.9.yml
  - .gitlab/ci/anolisos-7.9-custom-docker-repo-type.yml
  - .gitlab/ci/anolisos-7.9-custom-kubernetes-images.yml
  - .gitlab/ci/anolisos-7.9-custom-kubernetes-repo-type.yml
  - .gitlab/ci/anolisos-7.9-custom-kubernetes-version.yml
  - .gitlab/ci/ubuntu-22.04.yml
  - .gitlab/ci/ubuntu-22.04-custom-kubernetes-version.yml
  - .gitlab/ci/ubuntu-22.04-custom-kubernetes-version-suffix.yml
  # 同步代码
  - /sync.yml
