stages:
  # 准备系统环境
  - env
  # 安装 k8s
  - install
  # 代码同步
  - sync

# 嵌入
include:
  - .gitlab/ci/anolisos-7.9.yml
  - .gitlab/ci/anolisos-7.9-custom-docker-repo-type.yml
  - .gitlab/ci/anolisos-7.9-custom-kubernetes-repo-type.yml
  - .gitlab/ci/anolisos-7.9-custom-kubernetes-version.yml
  # 同步代码
  - /sync.yml
