stages:
  - install
  # 代码同步
  - sync

centos-7.9:
  stage: install
  script:
    - cat /etc/redhat-release
    - cat /etc/os-release
    - uname -a
    - chmod +x k8s.sh
    - echo "root" | script -qec "sudo -S ./k8s.sh kubernetes-taint calico-mirrors=hub-mirror.c.163.com"
    - source /etc/profile && source ~/.bashrc
    - kubectl get pod --all-namespaces -o wide
    - kubectl wait --for=condition=Ready --all pods --all-namespaces --timeout=600s
  tags:
    - ssh-centos-7.9

# 嵌入
include:
  # 同步代码
  - /sync.yml
