stages:
  # 准备系统环境
  - env
  # 安装 k8s
  - install
  # 代码同步
  - sync

variables:
  NEEDRESTART: n
  ANOLIS_URL: http://172.25.25.14:48081/repository/anolis
  CENTOS_URL: http://172.25.25.14:48081/repository/centos
  UBUNTU_URL: http://172.25.25.14:48081/repository/ubuntu

# 嵌入
include:
  - .gitlab/ci/anolis-7.9.yml
  - .gitlab/ci/anolis-7.9-custom-docker-repo-type.yml
  - .gitlab/ci/anolis-7.9-custom-docker-repo-type-private.yml
  - .gitlab/ci/anolis-7.9-custom-k8s-images.yml
  - .gitlab/ci/anolis-7.9-custom-k8s-repo-type.yml
  - .gitlab/ci/anolis-7.9-custom-k8s-repo-type-private.yml
  - .gitlab/ci/anolis-7.9-custom-k8s-version.yml
  - .gitlab/ci/anolis-7.9-custom-pause-image.yml
  - .gitlab/ci/centos-7.9.yml
  - .gitlab/ci/ubuntu-22.04.yml
  - .gitlab/ci/ubuntu-22.04-custom-docker-repo-type-private.yml
  - .gitlab/ci/ubuntu-22.04-custom-k8s-type-private.yml
  - .gitlab/ci/ubuntu-22.04-custom-k8s-version.yml
  - .gitlab/ci/ubuntu-22.04-custom-k8s-version-suffix.yml
  - .gitlab/ci/ubuntu-22.04-custom-pause-image.yml
  # 同步代码
  - /sync.yml
