stages:
  - env
  - install
  - env:custom
  - install:custom
  - env:kubernetes:1.28
  - install:kubernetes:1.28
  - env:kubernetes:1.27
  - install:kubernetes:1.27
  - env:kubernetes:1.26
  - install:kubernetes:1.26
  - env:kubernetes:1.25
  - install:kubernetes:1.25
  - env:kubernetes:1.24
  - install:kubernetes:1.24
  - pages
  - docker:build
  - docker:deploy
  - sync

variables:
  DOCKER_TAG: 2.0.0
  NEEDRESTART: n
  ANOLIS_URL: http://172.25.25.14:48081/repository/anolis
  CENTOS_URL: http://172.25.25.14:48081/repository/centos
  CENTOS_VAULT_URL: http://172.25.25.14:48081/repository/centos-vault
  CENTOS_STREAM_URL: http://172.25.25.14:48081/repository/centos-stream
  CENTOS_STREAM_SIGS_URL: http://172.25.25.14:48081/repository/centos-stream-SIGs
  UBUNTU_URL: http://172.25.25.14:48081/repository/ubuntu
  OPENEULER_URL: http://172.25.25.14:48081/repository/openeuler
  OPENKYLIN_URL: http://172.25.25.14:48081/repository/openkylin
  OPENKYLIN_ANYTHING_URL: http://172.25.25.14:48081/repository/openkylin-anything
  OPENKYLIN_ANYTHING_2_0_URL: http://172.25.25.14:48081/repository/openkylin-anything2.0
  OPENKYLIN_SOFTWARE_URL: http://172.25.25.14:48081/repository/openkylin-software
  OPENKYLIN_SOFTWARE_YANGTZE_URL: http://172.25.25.14:48081/repository/openkylin-software-yangtze

# 嵌入
include:
  - .gitlab/ci/almalinux-8.10.yml
  - .gitlab/ci/almalinux-9.4.yml
  - .gitlab/ci/almalinux-9.4-kubernetes-v1.24.yml
  - .gitlab/ci/almalinux-9.5.yml
  - .gitlab/ci/anolis-7.7.yml
  - .gitlab/ci/anolis-7.7-kubernetes-v1.24.yml
  - .gitlab/ci/anolis-7.7-kubernetes-v1.25.yml
  - .gitlab/ci/anolis-7.7-kubernetes-v1.26.yml
  - .gitlab/ci/anolis-7.7-kubernetes-v1.27.yml
  - .gitlab/ci/anolis-7.7-kubernetes-v1.28.yml
  - .gitlab/ci/anolis-7.7-kubernetes-v1.29.yml
  - .gitlab/ci/anolis-7.7-kubernetes-v1.30.yml
  - .gitlab/ci/anolis-7.9.yml
  - .gitlab/ci/anolis-7.9-custom-docker-repo-type.yml
  - .gitlab/ci/anolis-7.9-custom-docker-repo-type-private.yml
  - .gitlab/ci/anolis-7.9-custom-k8s-images.yml
  - .gitlab/ci/anolis-7.9-custom-k8s-repo-type.yml
  - .gitlab/ci/anolis-7.9-custom-k8s-repo-type-private.yml
  - .gitlab/ci/anolis-7.9-custom-k8s-version.yml
  - .gitlab/ci/anolis-7.9-custom-pause-image.yml
  - .gitlab/ci/anolis-7.9-kubernetes-v1.24.yml
  - .gitlab/ci/anolis-8.2.yml
  - .gitlab/ci/anolis-8.4.yml
  - .gitlab/ci/anolis-8.6.yml
  - .gitlab/ci/anolis-8.8.yml
  - .gitlab/ci/anolis-8.9.yml
  - .gitlab/ci/anolis-23.0.yml
  - .gitlab/ci/anolis-23.1.yml
  - .gitlab/ci/centos-7.9.yml
  - .gitlab/ci/centos-7.9-2207.yml
  - .gitlab/ci/centos-8.1.yml
  - .gitlab/ci/centos-8.2.yml
  - .gitlab/ci/centos-8.3.yml
  - .gitlab/ci/centos-8.4.yml
  - .gitlab/ci/centos-8.5.yml
  - .gitlab/ci/centos-9-20241028.0.yml
  - .gitlab/ci/centos-9-20241028.0-kubernetes-v1.24.yml
  - .gitlab/ci/debian-10.10.0.yml
  - .gitlab/ci/debian-10.10.0-kubernetes-v1.24.yml
  - .gitlab/ci/debian-11.7.0.yml
  - .gitlab/ci/debian-12.4.0.yml
  - .gitlab/ci/debian-12.7.0.yml
  - .gitlab/ci/deepin-20.9.yml
  - .gitlab/ci/kylin-v10-sp1-2403-20240430.yml
  - .gitlab/ci/kylin-v10-sp1-hwe-2303.yml
  - .gitlab/ci/openeuler-20.03.yml
  - .gitlab/ci/openeuler-22.03.yml
  - .gitlab/ci/openeuler-24.03.yml
  - .gitlab/ci/openkylin-1.0.1.yml
  - .gitlab/ci/openkylin-1.0.2.yml
  - .gitlab/ci/openkylin-1.0.yml
  - .gitlab/ci/openkylin-2.0.yml
  - .gitlab/ci/pages.yml
  - .gitlab/ci/rocky-8.10.yml
  - .gitlab/ci/rocky-9.4.yml
  - .gitlab/ci/rocky-9.5.yml
  - .gitlab/ci/sync.yml
  - .gitlab/ci/ubuntu-18.04.yml
  - .gitlab/ci/ubuntu-20.04.yml
  - .gitlab/ci/ubuntu-22.04.yml
  - .gitlab/ci/ubuntu-22.04-custom-docker-repo-type-private.yml
  - .gitlab/ci/ubuntu-22.04-custom-k8s-type-private.yml
  - .gitlab/ci/ubuntu-22.04-custom-k8s-version.yml
  - .gitlab/ci/ubuntu-22.04-custom-k8s-version-suffix.yml
  - .gitlab/ci/ubuntu-22.04-custom-pause-image.yml
  - .gitlab/ci/ubuntu-24.04.yml
  - .gitlab/ci/ubuntu-24.04-custom-cidr.yml
  - .gitlab/ci/ubuntu-24.04-custom-config.yml
  - .gitlab/ci/ubuntu-24.04-custom-control-plane-endpoint.yml
  - .gitlab/ci/ubuntu-24.04-custom-local-yaml.yml
  - .gitlab/ci/ubuntu-24.04-kubernetes-v1.24.yml
  - .gitlab/ci/ubuntu-kylin-18.04.5.yml
  - .gitlab/ci/ubuntu-kylin-20.04.6.yml
  - .gitlab/ci/ubuntu-kylin-22.04.5.yml
  - .gitlab/ci/ubuntu-kylin-24.04.1.yml
