stages:
  - install
  # 代码同步
  - sync

centos-7.9:
  stage: install
  variables:
    KUBECONFIG: /etc/kubernetes/admin.conf
  script:
    - cat /etc/redhat-release
    - cat /etc/os-release
    - uname -a
    - chmod +x k8s.sh
    - echo "root" | script -qec "sudo -S ./k8s.sh kubernetes-taint calico-mirrors=registry.jihulab.com/xuxiaowei-cloud/xuxiaowei-cloud && echo $KUBECONFIG && kubectl get pod --all-namespaces -o wide && kubectl wait --for=condition=Ready --all pods --all-namespaces --timeout=600s && kubectl get pod --all-namespaces -o wide"
  tags:
    - ssh-centos-7.9

# 嵌入
include:
  # 同步代码
  - /sync.yml
