stages:
  - install
  # 代码同步
  - sync

centos-7.9:
  stage: install
  script:
    - chmod +x k8s.sh
    - echo "root" | script -qec "sudo -S ./k8s.sh"
  tags:
    - ssh-centos-7.9

# 嵌入
include:
  # 同步代码
  - /sync.yml
