apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gitlab
  name: docker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      hostAliases:
        - ip: "172.25.25.220"
          hostnames:
            - "pig.docker.xuxiaowei.cn"
      containers:
        - name: docker
          image: docker:24.0.5-dind
          securityContext:
            privileged: true
          env:
            # 关闭 TLS（仅使用 http）
            - name: DOCKER_TLS_CERTDIR
              value: ""
          ports:
            - containerPort: 2375
            - containerPort: 2376
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: docker-certs
              # 信任域名证书的配置
              # 例如信任 pig.docker.xuxiaowei.cn 域名证书时，
              # 配置的路径为 /etc/docker/certs.d/pig.docker.xuxiaowei.cn/ca.crt，
              # 其中 ca.crt 文件为信任的域名证书，访问域名即可得到。
              # 说明：有端口时，记得文件夹要保留端口
              mountPath: /etc/docker/certs.d/
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: docker-certs
          nfs:
            path: /nfs/gitlab/docker/etc/docker/certs.d/
            server: 172.25.25.5

---

apiVersion: v1
kind: Service
metadata:
  namespace: gitlab
  name: docker-service
spec:
  selector:
    app: docker
  ports:
    - name: "2375"
      nodePort: 30375
      port: 2375
      targetPort: 2375
    - name: "2376"
      nodePort: 30376
      port: 2376
      targetPort: 2376
  type: NodePort
