apiVersion: v1
kind: Namespace
metadata:
  name: nexus

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nexus
  name: nexus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:3.58.1
          ports:
            # kubectl -n nexus port-forward svc/nexus 4800:8081 --address 0.0.0.0
            - containerPort: 8081
            - containerPort: 8443
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: nexus-data
          nfs:
            path: /nfs/nexus/nexus-data
            server: 172.25.25.5

---

apiVersion: v1
kind: Service
metadata:
  namespace: nexus
  name: nexus-service
spec:
  selector:
    app: nexus
  ports:
    - name: http
      nodePort: 31501
      port: 8081
      targetPort: 8081
    - name: https
      nodePort: 31502
      port: 8443
      targetPort: 8443
  type: NodePort
